definitions:
  handler.BaseResponse:
    properties:
      message:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: localhost:7070
info:
  contact: {}
  description: API Server for Application
  title: Elkonterm System API
  version: "1.0"
paths:
  /api/v1/admin/auth/login:
    post:
      consumes:
      - application/json
      description: Login Admin
      parameters:
      - description: Login Admin
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.BaseResponse'
      summary: Login Admin
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
